import React from 'react';
import Head from 'next/head'
import CountryList from '../components/CountryList'
import { Heading, Flex, Grid } from '@chakra-ui/react'
import ContinentSelector from '../components/ContinentSelector'

export default function Home() {
  const [selectedContinent, setselectedContinent] = React.useState("");

  return (
    <div>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid placeItems="center" maxW={800} width="100%" margin="0 auto 54px auto">
        <Flex marginY={10} justifyContent="center">
          <Heading>Countries</Heading>
        </Flex>
        <ContinentSelector onChange={(e) => setselectedContinent(e.target.value)}/>
        <CountryList selectedContinent={selectedContinent} />
      </Grid>
    </div>
  )
}
